version: "3"

services:
  app:
    ports:
      - "4000:4000"
      - "7777:7777"
    environment:
      NODE_ENV: development
    volumes:
      - ".:/usr/src/app"
      - /usr/src/app/node_modules
      - /usr/src/app/web/node_modules
      - /usr/src/app/server/node_modules
