version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./web/.env
    environment:
      MYSQL_HOST: algodb
      NODE_ENV: production
      WAIT_HOSTS: algodb:3306
    restart: always

  db:
    image: mysql:8.0.18
    env_file:
      - ./server/.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    container_name: algodb
    restart: always
